CREATE TABLE IF NOT EXISTS DEPARTMENT(
	DEPARTMENT_ID SERIAL,
	DEPARTMENT_NAME VARCHAR(64) UNIQUE NOT NULL,
	CONSTRAINT DEPARTMENT_PK PRIMARY KEY(DEPARTMENT_ID) 
);;
CREATE TABLE IF NOT EXISTS STUDENT(
	STUDENT_ID SERIAL,
   	FIRST_NAME VARCHAR(64) NOT NULL,
	LAST_NAME VARCHAR(64) NOT NULL,
	FATHER_NAME VARCHAR(128) NOT NULL,
	GENDER CHAR(1) NOT NULL,
	DOB DATE NOT NULL,
	ADDRESS VARCHAR(255) NOT NULL,	
	NATIONALITY VARCHAR(80) NOT NULL,
	STUDENT_PHONE VARCHAR(15),
	FATHER_PHONE VARCHAR(15),
	EMAIL VARCHAR(255),
	IDENTITY_TYPE VARCHAR(64),
	IDENTITY_NUMBER VARCHAR(20) UNIQUE,
	TAX_ID VARCHAR(20) UNIQUE,
	STIPEND NUMERIC(9,2),
	ACCOUNT_ID VARCHAR(26) UNIQUE,
	ACCOUNT_NAME VARCHAR(128),
	IFSC_CODE VARCHAR(11),
	DOJ DATE NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT NOW() NOT NULL,
	MODIFIED_TIME TIMESTAMP DEFAULT NOW(),
	DEPARTMENT_ID INTEGER NOT NULL,
	CONSTRAINT STUDENT_PK PRIMARY KEY(STUDENT_ID),
	CONSTRAINT STUDENT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);;
CREATE INDEX IF NOT EXISTS STUDENT_NAME_IDX ON STUDENT(FIRST_NAME,LAST_NAME);;




